
CREATE TEMP TABLE _migration (title_match TEXT, new_url TEXT, new_notes TEXT);
INSERT INTO _migration (title_match, new_url, new_notes) VALUES
('Desde mi columna, volumen 1', 'https://hdl.handle.net/20.500.12442/9225', ''),
('Desde mi columna, volumen 2', 'https://hdl.handle.net/20.500.12442/9226', 'El libro tiene un ISBN pero no aparece en la cámara del libro'),
('Desde mi columna, volumen 3', 'https://hdl.handle.net/20.500.12442/9227', ''),
('Desde mi Columna, volumen 4', 'https://hdl.handle.net/20.500.12442/9293', ''),
('Desde mi Columna, volumen 5', 'https://hdl.handle.net/20.500.12442/9294', ''),
('Evaluación de proyectos: estrategia empresarial', 'https://hdl.handle.net/20.500.12442/6213', ''),
('Diseño de proyectos', 'https://hdl.handle.net/20.500.12442/6212', ''),
('Administración financiera globalizada', 'https://hdl.handle.net/20.500.12442/6211', ''),
('Bicentenario de Colombia 1818-2010 Una visión compleja y crítica', '', 'No está en el repositorio. No hay ejemplares del libro.'),
('Las prácticas didácticas de las finanzas en un programa de administración de empresas', 'https://hdl.handle.net/20.500.12442/6202', ''),
('Biografías de instituciones educativas de la región caribe', 'http://en.rettalibros.com/shop/catalogs/show_material_details/56010', 'No se puede verificar. No se encuentra registro en web. No se encuentra ejemplar físico. Categorizado como libro.'),
('Derecho educativo', '', 'No se puede verificar. No se encuentra registro en web. No se encuentra ejemplar físico. Categorizado como libro.'),
('El discurso lógico y el discurso lógico-jurídico', 'http://hdl.handle.net/20.500.12442/1729', ''),
('Caracterización del sector artesanal latinoamericano', '', 'Categorizado como libro, no como capitulos'),
('Estado del arte del sector artesanal en latinoamerica. una mirada a través de la investigación realizada por ritfa', '', 'No se puede verificar, libro pago. Categorizado como libro, no se identifican los capitulos dentro del mismo.'),
('Prácticas educativas transcomplejas: una pedagogía emergente Tomo II', 'http://hdl.handle.net/20.500.12442/2651', 'No se encuentra registro en la base de datos categorizados'),
('Responsabilidad social empresarial como estratégia competitiva. un enfoque latinoamericano', 'https://biblioteca.ucatolica.edu.co/bib/80004', 'No se puede verificar, libro pago. No se encuentra en base de datos de productos categorizados.'),
('Teoría educativa transcompleja  Tomo I', 'http://hdl.handle.net/20.500.12442/2650', 'No se encuentra registro en la base de datos categorizados'),
('El caribe colombiano en la formación de la nación. el médico y prócer José Fernández Madrid', 'https://crai.ucompensar.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=9602', 'No se puede verificar. No se encuentra registro en web. No se encuentra ejemplar físico.'),
('Rutas por la memoria. familia y construcción de memorias: voces de nueva venecia y el salado', 'https://biblioteca.usco.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=37489%20thumbnail-shelfbrowser', 'Categorizado como libro, no como capitulos'),
('Bicentenario de Colombia (1810 - 2010) : Una visión dialéctica Tomo IV. Episodios nacionales II', 'http://hdl.handle.net/20.500.12442/1222', 'Categorizado como libro, no como capitulos'),
('Currículo transdisciplinar y práctica pedagógica compleja: (Emergencia y religantes de la educación del siglo XXI)', 'http://hdl.handle.net/20.500.12442/1197', 'Categorizado como libro, no como capitulos'),
('Aula mente social: Pensamiento transcomplejo Tomo III', 'http://hdl.handle.net/20.500.12442/1194', 'No se encuentra registro en la base de datos categorizados'),
('Currículo transcomplejo:  Pensamiento transcomplejo Tomo IV', 'http://hdl.handle.net/20.500.12442/1196', 'No se encuentra registro en la base de datos categorizados'),
('Factores asociados a la actividad física en personas de 18 a 69 años del distrito de Barranquilla.', 'http://hdl.handle.net/20.500.12442/1213', 'Categorizado como libro, no como capitulos'),
('¿Qué hacer con la identidad de género?: ¿Subvertirla, situarla o disolverla?. Reflexiones desde la filosofía crítica feminista', 'http://hdl.handle.net/20.500.12442/1296', 'Categorizado como libro, no como capitulos'),
('Administración pública: modernización del estado', 'http://hdl.handle.net/20.500.12442/1292', 'Categorizado como libro, no como capitulos'),
('Cultivo de bocachico en jagüeyes con alimentación natural. Estrategia empresarial para el sector agropecuario', 'https://es.scribd.com/document/341768175/Cultivo-Del-Bocachico-en-Jagueyes', ''),
('Gestión de procesos para el cultivo de bocachico en jagüeyes con la técnica estandarizada de fertilización al 2% en el municipio de piojo, departamento del atlántico', 'https://es.scribd.com/document/341768175/Cultivo-Del-Bocachico-en-Jagueyes', 'Categorizado como libro, no como capitulos'),
('Uso actual del suelo, tenencia de la tierra y conflictos del territorio en los departamentos de Atlántico y Bolívar: una reflexión', 'http://hdl.handle.net/20.500.12442/1291', ''),
('A la sombra de El Maestro', 'https://hdl.handle.net/20.500.12442/7679', ''),
('El conocimiento y la ciencia en el siglo XXI y sus dificultades estereognósicas', 'http://hdl.handle.net/20.500.12442/1293', ''),
('El incesto desde la perspectiva psicojurídica. Una mirada holística del delito para un tratamiento penitenciario eficaz', 'http://hdl.handle.net/20.500.12442/1295', ''),
('Contabilidad analítica: métodos cuantitativos para la ciencia contable', 'http://hdl.handle.net/20.500.12442/1300', 'Categorizado como libro, no como capitulos'),
('Cuee caribe: una estrategia para el impulso de la transferencia tecnológica en el caribe colombiano', 'http://hdl.handle.net/20.500.12442/1353', ''),
('Cultura de paz y derechos humanos. Una mirada socio-jurídica', 'http://hdl.handle.net/20.500.12442/1298', 'No se encuentra registro en la base de datos categorizados'),
('Currículo y saberes en la formación de abogados: propuestas alternativas para pensar la educación jurídica', 'http://hdl.handle.net/20.500.12442/1297', 'Categorizado como libro, no como capitulos'),
('Discurso, compromiso e historia. una aproximación sociológica al trabajo intelectual y político', 'http://hdl.handle.net/20.500.12442/1208', 'No se encuentra registro en la base de datos categorizados'),
('El contexto discursivo de la educación: una reflexión desde la investigación y práctica docente', 'https://ocs.unicesar.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=23726', 'No se puede verificar, libro pago.Categorizado como libro, no como capitulo.'),
('Estilos de enseñanza y docencia universitaria', 'http://hdl.handle.net/20.500.12442/1205', 'Categorizado como libro, no como capitulos'),
('Estudios jurídicos contemporáneos', 'http://www.rettalibros.com/shop/catalogs/show_material_details/59139', 'No se puede verificar, libro pago. No se encuentra en BD de productos categorizados. No registra financiación'),
('Grupo neurociencias del Caribe: trayectoria investigativa 2009-2014', 'http://hdl.handle.net/20.500.12442/1294', ''),
('José Fernández Madrid: Ilustración, Patriotismo y Tragedia', 'http://hdl.handle.net/20.500.12442/1299', 'Categorizado como libro, no como capitulos'),
('Saberes y formación ciudadana: enfoques socio educativos e históricos', 'https://coruniamericana.metacatalogo.org/bib/62473', 'No se puede verificar, libro pago. No se encuentra en BD de productos categorizados. No registra financiación'),
('Violencias, nuevas subjetividades y política de civilización.', 'http://hdl.handle.net/20.500.12442/1199', 'No se encuentra registro en la base de datos categorizados'),
('Curso básico de responsabilidad social empresarial', 'https://hdl.handle.net/20.500.12442/3540', ''),
('Gestión del talento: un análisis desde múltiples enfoques', '', 'No se puede verificar, libro pago. No se encuentra en base de datos de productos categorizados.'),
('¿Qué son las ciencias sociales y humanas?', '', 'No se puede verificar, libro pago. No reporta financiación'),
('Género y Ciencias Sociales. Fronteras flexibles y fluidas', 'http://hdl.handle.net/20.500.12442/1200', 'No se encuentra registro en la base de datos categorizados'),
('Género y discurso : fuerzas regulatorias dominantes y márgenes de gestión de las autonomías', 'http://hdl.handle.net/20.500.12442/1211', 'PDF no disponible en Bonga'),
('Líderes empresariales del Caribe', 'https://hdl.handle.net/20.500.12442/3541', ''),
('Manual de evaluación de documentos científicos', 'http://hdl.handle.net/20.500.12442/1153', ''),
('Intercambio dialógico entre las académicas y las artistas: performances colaborativos', 'https://beta.acuedi.org/storage/books/pdf/10231.pdf', 'Categorizado como libro, no como capitulos'),
('Marcapasos cardiaco', 'http://hdl.handle.net/20.500.12442/1143', 'Categorizado como libro, no como capitulos'),
('Pensar el horizonte pedagógico socio crítico', 'https://coruniamericana.metacatalogo.org/bib/62571', 'No se puede acceder a mayor información. Libro pago.'),
('Bolívar habla de sí mismo', '', 'No se puede acceder a mayor información. Libro pago. No se encuentra registrado en la BD de libros categorizados.'),
('Conceptos Jurídicos, Tomo II', '', 'No se puede acceder a mayor información. Libro pago. No se encuentra registrado en la BD de libros categorizados.'),
('El camino propio hacia el desarrollo', 'https://hdl.handle.net/20.500.12442/9295', 'No se encuentra registro en la base de datos categorizados'),
('El mobbing o acoso laboral', '', 'No se encuentra información del libro. No se encuentra registrado en la base de datos de libros categorizados'),
('Aproximaciones al pensamiento bolivariano', 'http://hdl.handle.net/20.500.12442/1147', 'Categorizado como libro, no como capitulos'),
('Contextos de la educación no formal, actual educación para el trabajo y el desarrollo humano. huellas de su desarrollo y transformación en cúcuta', 'http://hdl.handle.net/20.500.12442/1150', 'No se puede verificar, libro pago. Categorzado como libro, no como capítulos'),
('En la Onda de los Recursos Hídricos', '', 'No se puede acceder a mayor información. Libro pago. No se encuentra registrado en la BD de libros categorizados.'),
('Guía de la investigación como estrategia pedagógica', '', 'Libro impreso, no se puede verificar, ni acceder a mayor información.'),
('José consuegra higgins: su vida y su legado', 'https://politeca.uniboyaca.edu.co/bib/20892', 'No se puede acceder a mayor información. Libro pago. No se encuentra registrado en la BD de libros categorizados.'),
('Las ondas en la primera infancia en el Atlántico', 'http://hdl.handle.net/20.500.12442/1130', ''),
('Religaje educativo : Espacio-Tiempo. Tomo V', 'http://hdl.handle.net/20.500.12442/1204', ''),
('Actitudes y prácticas frente al cáncer de cuello uterino.', 'http://hdl.handle.net/20.500.12442/1192', ''),
('Bicentenario de Colombia (1810-2010): Tomo V. La historia de los vencidos 1', 'http://hdl.handle.net/20.500.12442/1728', 'Categorizado como libro, no como capitulos'),
('Comportamiento innovador en el sector alimentos en el Distrito de Barranquilla.', 'http://hdl.handle.net/20.500.12442/1193', ''),
('Contabilidad de gestión : desde la medición del valor hacia el uso eficiente de los recursos.', 'http://hdl.handle.net/20.500.12442/1195', 'Categorizado como libro, no como capitulos'),
('Derecho procesal y perspectiva científica de la prueba', 'http://hdl.handle.net/20.500.12442/1137', 'No se encuentra registro en la base de datos categorizados'),
('Diseño a fatiga de un perno de apriete', 'http://hdl.handle.net/20.500.12442/1203', 'Categorizado como libro, no como capitulos'),
('Economía pública', 'http://hdl.handle.net/20.500.12442/1210', 'No se encuentra registro en la base de datos categorizados'),
('El discurso retórico o el arte de persuadir en el campo político, forense, pedagógico y religioso', 'http://hdl.handle.net/20.500.12442/1198', ''),
('Estudios actuales en psicología', 'http://hdl.handle.net/20.500.12442/1126', ''),
('Formulación y evaluación de proyectos: soporte de la planeación', 'http://hdl.handle.net/20.500.12442/1129', ''),
('Gestión de marketing para el sector agroindustrial', 'http://hdl.handle.net/20.500.12442/1206', 'No se encuentra registro en la base de datos categorizados'),
('Identidad, conflicto y afrodescendencia en el caribe colombiano', 'http://hdl.handle.net/20.500.12442/1134', ''),
('La construcción colectiva en ciencias sociales humanas.', 'http://hdl.handle.net/20.500.12442/1191', ''),
('La contabilidad a valor razonable. Mediciones contables conforme a datos del mercado', 'http://hdl.handle.net/20.500.12442/1140', 'Categorizado como libro, no como capitulos'),
('Macroeconomía intermedia. Principios básicos para la modelación macroeconómica, una aplicación en STATA', 'http://hdl.handle.net/20.500.12442/2298', 'No se encuentra registro en la base de datos categorizados'),
('Manual para Pacientes con Enfermedad Renal Crónica', '', 'Libro impreso, no se puede acceder a mayor información. No se encuentra registro en BD de productos categorizados'),
('Matices y horizonte de la investigación en trabajo social', 'http://hdl.handle.net/20.500.12442/1144', 'No se encuentra registro en la base de datos categorizados'),
('Modelo de microcrédito y reflexiones de expertos financieros', 'http://hdl.handle.net/20.500.12442/1125', 'Categorizado como libro, no como capitulos'),
('Neuropsicología de las funciones ejecutivas', 'http://hdl.handle.net/20.500.12442/1209', ''),
('Patria Potestad abordaje teórico en Colombia y Venezuela', 'http://hdl.handle.net/20.500.12442/1151', 'No se encuentra categoizado como libro'),
('Pequeños asesinos. Mitos y realidades de los parásitos y la parasitosis intestinal', '', 'Libro impreso, no se puede acceder a mayor información'),
('Potencial exportador del departamento del Atlántico', 'http://hdl.handle.net/20.500.12442/1202', ''),
('Propagación de ondas en el atlántico 2012-2013', 'http://hdl.handle.net/20.500.12442/2776', ''),
('Reflexiones educativas y pedagógicas desde la investigación', 'http://hdl.handle.net/20.500.12442/1132', 'Categorizado como libro, no como capitulos'),
('Registro civil: abordaje teórico en Colombia y Venezuela', 'http://hdl.handle.net/20.500.12442/1148', 'No se encuentra registro en la base de datos categorizados'),
('Saber y práctica pedagógica', 'http://hdl.handle.net/20.500.12442/1133', 'Categorizado como libro, no como capitulos'),
('La búsqueda de una concepción integral del desarrollo', '', 'Libro impreso, no se puede acceder a mayor información.'),
('Manual de propiedad intelectual, plagio y fraude académico', 'http://hdl.handle.net/20.500.12442/1145', 'Categorizado como libro, no como capitulos'),
('Temas claves de responsabilidad social empresarial', 'https://hdl.handle.net/20.500.12442/3547', 'No se encuentra registro en base de datos de productos categorizados'),
('Ciencia e Innovación. Capacidades al Servicio de la Sociedad', '', 'Libro impreso, no se puede acceder a mayor información. No se encuentra registro en BD de productos categorizados'),
('Gestión de la responsabilidad social de la empresa ante la sociedad', 'https://hdl.handle.net/20.500.12442/3546', 'No se encuentra registro en base de datos de productos categorizados'),
('Género y ciencias sociales. Arqueología y cartografías de fronteras', 'http://hdl.handle.net/20.500.12442/1128', ''),
('La cultura organizacional, elemento fundamental en la calidad universitaria', 'http://hdl.handle.net/20.500.12442/1141', 'No se encuentra registro en base de datos de productos categorizados'),
('Artes en femenino investigaciones situadas y performances colaborativos', 'http://hdl.handle.net/20.500.12442/1135', ''),
('Deshilando las violencias de género y construyendo centros de resistencias', 'http://hdl.handle.net/20.500.12442/1138', ''),
('Electrocardiografía: aspectos prácticos para el médico no especialista', 'http://hdl.handle.net/20.500.12442/1124', 'No se encuentra registro en base de datos de productos categorizados'),
('La Teoría Propia en la obra de José Consuegra Higgins', '', 'Libro impreso, no se puede acceder a mayor información. No hay registro en la BD de productos categorizados.'),
('Análisis del contrabando en el norte de santander, desde la percepción de los constructos de la institucionalidad', 'http://hdl.handle.net/20.500.12442/1146', 'Categorizado como libro, no como capitulos'),
('Fronteras educativas desde la perspectiva psicológica: escuela, familia y tecnología. Aliados en educación', 'http://hdl.handle.net/20.500.12442/1123', 'No hay registro en la base de datos de productos categorizados'),
('Violencia sexual & conflicto armado : aproximación psicojurídica.', 'http://hdl.handle.net/20.500.12442/1201', ''),
('Ensayos sobre cultura popular caribeña', 'https://catalogobibliografico.cuc.edu.co/bib/43336', 'No se pudo verificar categoria Minciencias-editorial externa'),
('José consuegra higgins: Escritos desde la trinchera', 'https://hdl.handle.net/20.500.12442/9217', 'No hay registro en la base de datos de productos categorizados'),
('The war, the women, their bodies : researches and experiences on Africa, America, Asia and Europe.', 'http://hdl.handle.net/20.500.12442/1207', 'No hay registro en la base de datos de productos categorizados'),
('El desarrollo profesional del profesorado. experiencias desde la investigación-acción', 'https://biblioteca.unimeta.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=11011&query_desc=su%3A%22Investigaci%C3%B3nes%22', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Análisis multivariado de datos', '', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Cuando la literatura en Barranquilla le dio la vuelta al tiempo crónicas y ensayos sobre sus personajes', 'https://catalogobibliografico.cuc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=38424&query_desc=an%2Cphr%3A%2034276', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Estilos de vida saludable para superhéroes', 'http://hdl.handle.net/20.500.12442/2375', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Publicidad: Abordajes epistemológicos, creatividad, consumo y marca', 'https://www.ucm.edu.co/publicidad-abordajes-epistemologicos-creatividad-consumo-y-marca/', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Resultados de investigación en estilos de vida saludable', 'http://hdl.handle.net/20.500.12442/2374', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Nosotros los del caribe', 'http://hdl.handle.net/20.500.12442/1127', ''),
('Ensayos sobre el desarrollo de América Latina', '', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Pensadores sociales latinoamericanos', '', 'No se pudo verificar categoria Minciencias-editorial externa'),
('El Ecosistema de Ciberseguridad de Colombia', '', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Maestros de la responsabilidad social empresarial', 'https://hdl.handle.net/20.500.12442/3545', ''),
('Percepción de los habitantes de las subregiones del norte de santander frente al contrabando', 'http://hdl.handle.net/20.500.12442/1131', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Amor, protección y sexo', '', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Introducción a la responsabilidad social universitaria RSU', 'https://hdl.handle.net/20.500.12442/3544', 'No se pudo verificar categoria Minciencias-editorial externa'),
('La problemática de identidad, la historia y la etnoeducación en los afroatlanticenses', 'http://hdl.handle.net/20.500.12442/1122', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Metodología para la evaluación del impacto de los proyectos emergentes de proyección social', 'http://hdl.handle.net/20.500.12442/1149', ''),
('Diseño de Ambientes de Enseñanza-Aprendizaje: Consideraciones con base en la PNL y los Estilos de Aprendizaje', '', 'No se pudo verificar categoria Minciencias-editorial externa'),
('América latina: entre revoluciones y la búsqueda de la paz', 'http://hdl.handle.net/20.500.12442/1838', ''),
('Aportes a la calidad educativa desde la investigación', 'http://hdl.handle.net/20.500.12442/1769', ''),
('Aspectos jurídicos de la conciliación prejudicial contenciosa administrativa en colombia', 'http://hdl.handle.net/20.500.12442/1777', ''),
('Caracterización de la discapacidad en el distrito de Barranquilla. Una mirada conceptual y experiencial', 'http://hdl.handle.net/20.500.12442/2300', ''),
('Carnaval de Barranquilla: patrimonio musical y danzario del Caribe Colombiano', 'http://hdl.handle.net/20.500.12442/2109', ''),
('Cómo crear un servicio de telemedicina. Revisión sistemática y análisis para su implementación', 'http://hdl.handle.net/20.500.12442/1288', ''),
('Competitividad e innovación: el poder competitivo de la innovación', 'http://hdl.handle.net/20.500.12442/2280', ''),
('Construyendo caminos de bienestar: un programa psicoeducativo a partir de la relación del bienestar psicológico con el rendimiento académico', 'http://hdl.handle.net/20.500.12442/1834', ''),
('Contabilidad de las combinaciones de negocios y de acuerdos conjuntos: las fusiones, escisiones, consolidaciones y conversiones de los estados financieros de filiales, subsidiarias y asociadas', 'http://hdl.handle.net/20.500.12442/1279', ''),
('Contexto educativo: convergencias y retos desde la perspectiva psicológica', 'http://hdl.handle.net/20.500.12442/1158', ''),
('Currículo y pedagogía: abordajes teóricos y conceptuales para la investigación educativa', 'https://hdl.handle.net/20.500.12442/6731', ''),
('De algunos de los protagonistas del segundo milenio. Tomo V', 'http://hdl.handle.net/20.500.12442/1730', 'No se pudo verificar categoria Minciencias-editorial externa'),
('De la transferencia tecnológica a la innovación. Un desafío para las universidades en el siglo XXI', 'https://hdl.handle.net/20.500.12442/9616', ''),
('El derecho de los niños y niñas a conocer su diagnóstico de VIH/SIDA: La revelación del diagnóstico a través del modelo clínico "DIRÉ"', 'http://hdl.handle.net/20.500.12442/1139', 'no se pudo verificar categoria Minciencias'),
('Desarrollo organizacional y gestión humana en contextos globalizados', 'http://hdl.handle.net/20.500.12442/2602', ''),
('Desarrollo y gestión de la producción de bocachico en jagüeyes en el departamento del Atlántico: Prochilodus magdalenae, Steindachner, 1878', 'https://hdl.handle.net/20.500.12442/6617', ''),
('Didáctica y gerencia en el uso educativo de tecnologías de información y comunicación (tic) en educación básica secundaria', 'http://hdl.handle.net/20.500.12442/1157', ''),
('Direccionamiento estratégico y aprendizaje', 'http://hdl.handle.net/20.500.12442/1283', ''),
('Diseño del pendolón de un puente colgante', 'http://hdl.handle.net/20.500.12442/1285', ''),
('Economía naranja: un potencial para el desarrollo del Caribe Colombiano', 'https://hdl.handle.net/20.500.12442/5947', ''),
('Educación y contextos sociales', 'http://hdl.handle.net/20.500.12442/1905', ''),
('Educación, desarrollo y representaciones sociales: estudios interdisciplinarios del caribe', 'http://hdl.handle.net/20.500.12442/2203', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Ejercicio físico para la condición física funcional en el adulto mayor: estrategia de intervención', 'http://hdl.handle.net/20.500.12442/2611', ''),
('El accionar contable del libertador ante la crisis económico-política del proyecto republicano de la Gran Colombia (1827-1830)', 'http://hdl.handle.net/20.500.12442/1374', ''),
('El discurso filosófico frente a la paz: primera parte', 'http://hdl.handle.net/20.500.12442/1727', 'No se pudo verificar categoria Minciencias-editorial externa'),
('El patrimonio cultural desde diversas miradas. Casos de estudio en Hispanoamérica', 'https://hdl.handle.net/20.500.12442/9621', 'No se pudo verificar categoria Minciencias-editorial externa'),
('ERP, el sistema de Planificación de los Recursos de la Empresa. Un sistema integrado de información configurado por el sistema de información contable y el sistema de información gerencial.', 'http://hdl.handle.net/20.500.12442/1557', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Estrategias de indagación científica. El método como estrategia', 'http://hdl.handle.net/20.500.12442/1142', ''),
('Estudio de mercado para proyecto de doctorado en administración de empresas e innovación', 'http://hdl.handle.net/20.500.12442/2617', ''),
('Estudios actuales en psicología: perspectivas en clínica y salud', 'http://hdl.handle.net/20.500.12442/1120', ''),
('Estudios de casos en seguridad y salud en el trabajo: una experiencia de formación en investigación', 'http://hdl.handle.net/20.500.12442/2952', ''),
('Estudios de competitividad y análisis empresarial en la región caribe', 'http://hdl.handle.net/20.500.12442/2953', ''),
('Formación y problemáticas sociales: hacia la construcción de propuestas curriculares contextualizadas y pertinentes', 'https://hdl.handle.net/20.500.12442/9346', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Gerencia de las organizaciones. Un enfoque empresarial', 'http://hdl.handle.net/20.500.12442/2824', ''),
('Gerencia empresarial. una perspectiva integral desde lo público y privado', 'https://hdl.handle.net/20.500.12442/3219', ''),
('Gestión contable y financiera en organizaciones. Un enfoque global', 'http://hdl.handle.net/20.500.12442/2621', ''),
('Gestión del conocimiento y capacidad de innovación: Modelos, Sistemas y Aplicaciones', 'http://hdl.handle.net/20.500.12442/2089', ''),
('Herramientas para la gestión de la productividad en la empresa: experiencias exitosas desde el Caribe colombiano', 'http://hdl.handle.net/20.500.12442/1836', ''),
('Identidades y expectativas de paz: aportes desde las ciencias sociales y humanas', 'http://hdl.handle.net/20.500.12442/2005', ''),
('Introducción al estudio de las matemáticas financieras', 'http://hdl.handle.net/20.500.12442/1287', ''),
('Investigaciones y casos del sector salud en la región caribe', 'http://hdl.handle.net/20.500.12442/2609', ''),
('La gestión cultural: laboratorio social para el desarrollo del caribe', 'http://hdl.handle.net/20.500.12442/2624', 'No se pudo verificar categoria Minciencias-editorial externa'),
('La gestión curricular como investigación para el desarrollo y fortalecimiento de los procesos de formación en las organizaciones educativas', '', 'No se pudo verificar la editorial'),
('La investigación en los programas de administración de empresas de la región caribe colombiana', 'https://hdl.handle.net/20.500.12442/6241', ''),
('LAMARK : una mirada cualitativa para construir marca ciudad', 'http://hdl.handle.net/20.500.12442/1930', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Las capacidades dinámicas: desarrollos teóricos y evidencias empíricas', 'https://hdl.handle.net/20.500.12442/8338', ''),
('Marketing y competitividad en las organizaciones: enfoques y perspectivas', 'http://hdl.handle.net/20.500.12442/2202', ''),
('Modelo por Competencias: para mejorar la competitividad académica en el programa de Administración de Empresas', 'http://hdl.handle.net/20.500.12442/1352', ''),
('Mujeres ancestrales. Mujeres formadas para visibilizar la cultura ancestral del Atlántico hacia una vida libre de violencias y sin discriminación', 'https://hdl.handle.net/20.500.12442/6798', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Perspectivas ambientales contemporáneas', 'https://hdl.handle.net/20.500.12442/4696', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Perspectivas empresariales e inclusivas del emprendimiento', 'http://hdl.handle.net/20.500.12442/2604', ''),
('Polifonía Caribe: un concierto interdisciplinario', 'http://hdl.handle.net/20.500.12442/2110', ''),
('Proceso de internacionalización de las pymes', 'http://hdl.handle.net/20.500.12442/2090', ''),
('Productos de confitería nutracéutica y biofertilizantes: una opción empresarial para cultivadores de frutas y hortalizas', 'http://hdl.handle.net/20.500.12442/2204', ''),
('Programa de articulación de las funciones de docencia, investigación, extensión y proyección social (PADIE). Un enfoque desde la Facultad de Administración y Negocios', 'http://hdl.handle.net/20.500.12442/2614', ''),
('Propagación de ONDAS en el Atlántico 2014', 'http://hdl.handle.net/20.500.12442/2779', ''),
('Real-Time PCR applied to bacterial waterborne pathogens detection and quantification', 'http://hdl.handle.net/20.500.12442/2616', ''),
('Rehabilitación cardíaca basada en un programa de ejercicio físico en sujetos con revascularización miocárdica', 'https://hdl.handle.net/20.500.12442/3223', ''),
('Reinventando saberes para la intervención social', 'http://hdl.handle.net/20.500.12442/1280', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Representaciones femeninas e interculturales en gobiernos escolares', 'http://hdl.handle.net/20.500.12442/2206', ''),
('Respeto por la dignidad y la diversidad: mecanismos para la garantía de los derechos de las mujeres y las personas lgbti en el distrito de barranquilla', 'http://hdl.handle.net/20.500.12442/1977', ''),
('Tendencias nacionales e internacionales en la formación de abogados', '', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Turismo corporativo y TIC: una puerta a la competitividad. Dinámicas sectoriales que estimulan la competencia colaborativa apoyada en las tecnologías de la información y las comunicaciones', 'http://hdl.handle.net/20.500.12442/2620', ''),
('Universidad - ciencia - innovación y sociedad: desde la perspectiva laboral', 'https://www.uajs.edu.co/sites/default/files/investigacion/fimov/capitulos/UNIVERSIDAD,%20CIENCIA,%20INNOVACI%C3%93N%20Y%20SOCIEDAD.pdf', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Vivencias de las mujeres en relación con las intervenciones médicas durante el embarazo y el parto', 'http://hdl.handle.net/20.500.12442/1284', ''),
('Prácticas pedagógicas', 'http://hdl.handle.net/20.500.12442/2099', ''),
('Norte de Santander y Táchira: más que un límite fronterizo, subjetividades construidas en el territorio', 'http://hdl.handle.net/20.500.12442/2093', ''),
('Políticas públicas: desafíos en Colombia y Venezuela', 'http://hdl.handle.net/20.500.12442/2096', ''),
('Las tecnologías de información y comunicación y la gestión empresarial', 'http://hdl.handle.net/20.500.12442/2105', ''),
('Estudios latinoamericanos transfronterizos y desarrollo de capacidades humanas', 'http://hdl.handle.net/20.500.12442/2100', ''),
('Maternidad adolescente en el Norte de Santander', 'http://hdl.handle.net/20.500.12442/2095', ''),
('Encrucijadas pedagógicas: resignificación, emergencias y praxis educativa', 'http://hdl.handle.net/20.500.12442/2106', ''),
('Metodología de investigación con contenidos estadísticos para el Programa de Ingeniería de Sistemas de la Universidad Simón Bolívar.', 'http://hdl.handle.net/20.500.12442/2098', ''),
('De un determinismo a otro: 2500 años de prejuicios sociales', 'http://hdl.handle.net/20.500.12442/2102', ''),
('Derechos humanos desde una perspectiva socio-jurídica', 'http://hdl.handle.net/20.500.12442/2097', ''),
('Gestión social comunitaria', 'http://hdl.handle.net/20.500.12442/2101', ''),
('Educación inclusiva', 'http://hdl.handle.net/20.500.12442/2104', ''),
('Caracterización cognitiva, afectiva y social en la identidad del Cucuteño y el Nortesantandereano', 'http://hdl.handle.net/20.500.12442/2094', ''),
('La base de la pirámide y la innovación frugal en América Latina', 'http://hdl.handle.net/20.500.12442/2103', ''),
('Guía de práctica clínica para glomerulonefritis membranoproliferativa', 'https://hdl.handle.net/20.500.12442/11228', ''),
('Guía de práctica clínica para glomerulonefritis membranosa', 'https://hdl.handle.net/20.500.12442/11232', ''),
('Guía en práctica en trasplante renal', 'https://bonga.unisimon.edu.co/server/api/core/bitstreams/d8d4b513-58b7-448c-abe7-390e11fdd777/content', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Guía para el manejo de anestesia en trasplante renal', 'https://hdl.handle.net/20.500.12442/11233', ''),
('Guía para la prevención de infecciones por catéteres', 'https://hdl.handle.net/20.500.12442/11230', ''),
('Manual de producción de Jaiba Blanda (Callinectes Bocourti)', 'https://hdl.handle.net/20.500.12442/3222', ''),
('Perfume de colombia con aroma a vallenato', 'https://biblioteca.comfamiliar.com.co/pmb/opac_css/index.php?lvl=notice_display&id=48130', ''),
('Propuesta de un modelo de gestión de salud de la nefritis lúpica basado en la problemática clínica y su impacto socio-sanitario en la región caribe colombiana', 'http://hdl.handle.net/20.500.12442/1187', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Sexualidad, pobreza, violencias y estereotipos: una mirada desde los jóvenes a los estudios de género', 'http://hdl.handle.net/20.500.12442/2107', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Liderazgo y participación política de las mujeres en américa latina en el siglo xxi', 'http://hdl.handle.net/20.500.12442/2354', ''),
('Avances en investigación de operaciones y ciencias administrativas', 'http://hdl.handle.net/20.500.12442/2091', ''),
('Tele-rehabilitación, dinamizadora del modelo de atención en salud', 'https://hdl.handle.net/20.500.12442/5186', ''),
('Perfil emprendedor del estudiante de las facultades de administración, adscritas al capítulo oriente de ascolfa', 'https://hdl.handle.net/20.500.12442/6558', 'No se pudo verificar categoria Minciencias'),
('Estudios doctorales femeninos: aportes desde las ciencia sociales y humanas', 'http://hdl.handle.net/20.500.12442/2205', ''),
('Las ciencias sociales en sus desplazamientos: nuevas epistemes y nuevos desafíos', 'http://hdl.handle.net/20.500.12442/2120', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Unidad de apoyo al microempresario : hacia la construcción de microempresas sostenibles en Barranquilla', 'http://hdl.handle.net/20.500.12442/1373', ''),
('Aplicaciones básicas sobre la jurisdicción especial para la paz', '', 'Ejemplar no dispoible'),
('Ciencia, tecnología y desarrollo social volumen I', '', 'Ejemplar no dispoible'),
('Desafíos del derecho frente al posconflicto', '', 'No se pudo verificar categoria Minciencias-editorial externa'),
('Experiencias significativas en el acceso a la justicia desde las prácticas de consultorio jurídico y centro de conciliación de la Corporación Universitaria del Caribe-CECAR: Años 2013-2016', '', 'No se pudo verificar categoria Minciencias-editorial externa'),
('En todos los colores cartografías del género y las sexualidades en hispanoamérica', 'http://hdl.handle.net/20.500.12442/2281', ''),
('Electrocardiografía. nuevos avances', 'http://hdl.handle.net/20.500.12442/2820', ''),
('Informe sobre la movilidad humana venezolana. Realidades y perspectivas de quienes emigran (9 de abril al 6 de mayo de 2018)', 'https://hdl.handle.net/20.500.12442/4619', ''),
('La investigación educativa: reconociendo la escuela para transformar la educación', 'http://hdl.handle.net/20.500.12442/2275', ''),
('Propagación de ondas en el atlántico 2015', 'https://hdl.handle.net/20.500.12442/3955', ''),
('La hegemonía del management', 'https://libreriasiglo.com/46266-la-hegemonia-del-management?srsltid=AfmBOorg6hxci4j5J19pKPlY_OgP5pcmqmWZXXvaDZ1y9M6lEwa2ZzGW', ''),
('Aspectos básicos en obesidad', 'http://hdl.handle.net/20.500.12442/2273', ''),
('Orientaciones para la educación sanitaria mediada por las tecnologías móviles', 'https://hdl.handle.net/20.500.12442/3923', ''),
('Adolescencia: su relación con la familia, educación y sexualidad. Un enfoque transdisciplinario', 'http://hdl.handle.net/20.500.12442/2817', ''),
('Adolescencia: vulnerabilidades. Una mirada interdisciplinaria', 'http://hdl.handle.net/20.500.12442/2331', ''),
('Apropiación cultural caribe', 'https://hdl.handle.net/20.500.12442/7057', ''),
('Comprensión de relatos infantiles del caribe: la palabra viva', 'http://hdl.handle.net/20.500.12442/2955', ''),
('Desafiando a la inequidad de Latinoamérica: estrategias facilitadoras de “control” de la Enfermedad Renal Crónica', 'http://hdl.handle.net/20.500.12442/2283', ''),
('Educación socio-ambiental. Acción - Presente', 'http://hdl.handle.net/20.500.12442/2606', ''),
('Emprendimiento, empleabilidad y política: una mirada globalizadora', 'http://hdl.handle.net/20.500.12442/2652', ''),
('Epistemología del caribe', '', 'No en el repositorio'),
('Estrategias para la permanencia estudiantíl universitaria', 'http://hdl.handle.net/20.500.12442/2330', ''),
('Fragmentos históricos', 'https://hdl.handle.net/20.500.12442/4382', ''),
('Innovación psicológica: conflicto y paz', 'http://hdl.handle.net/20.500.12442/2543', ''),
('Innovación psicológica: salud, educación y cultura', 'http://hdl.handle.net/20.500.12442/2580', ''),
('Investigación y praxis en la enseñanza de las matemáticas', 'https://hdl.handle.net/20.500.12442/3204', ''),
('La investigación jurídica: reconociendo acciones normativas relevantes', 'http://hdl.handle.net/20.500.12442/2289', ''),
('La investigación sociojurídica: un análisis de la incidencia de los aspectos sociales para el derecho', 'http://hdl.handle.net/20.500.12442/2274', ''),
('Mujer, emprendimiento y empleabilidad: una mirada interdisciplinaria', 'http://hdl.handle.net/20.500.12442/2332', ''),
('Nuevas tendencias en investigación de operaciones y ciencias administrativas. Un enfoque desde estudios iberoamericanos', 'http://hdl.handle.net/20.500.12442/2601', ''),
('Nuevo liderazgo político para una nueva arquitectura institucional', 'http://hdl.handle.net/20.500.12442/2954', ''),
('Pedagogías contemporáneas: miradas divergentes al mundo escolar', 'https://hdl.handle.net/20.500.12442/3288', ''),
('Universidad, organizaciones y competencias genéricas. Una alianza de éxito para el siglo XXI', 'http://hdl.handle.net/20.500.12442/2649', ''),
('VIH/SIDA Mitos y Verdades', 'http://hdl.handle.net/20.500.12442/2323', 'Es una cartilla'),
('Recomendaciones y actualizaciones en atención para el manejo de pacientes vih positivo', 'http://hdl.handle.net/20.500.12442/2322', ''),
('El papel de la contabilidad de gestión en la formación de los contadores públicos: caso región caribe colombia', 'http://hdl.handle.net/20.500.12442/2613', ''),
('Yo amo la ciencia: construyendo una cultura de ciencia e innovación en el Atlántico', 'http://hdl.handle.net/20.500.12442/2781', ''),
('Actores en la educación: una mirada desde la psicología educativa', 'http://hdl.handle.net/20.500.12442/2490', ''),
('Aportes a la gestión de los recursos hídricos en el departamento del atlántico', 'https://hdl.handle.net/20.500.12442/3830', ''),
('Apuntes perspectiva de innovación pedagógica para la construcción de competencias ciudadanas', 'https://hdl.handle.net/20.500.12442/3777', ''),
('Aspectos tributarios y financieros: una mirada desde lo público y privado Latinoamérica y el Caribe', 'https://hdl.handle.net/20.500.12442/9609', ''),
('Bienestar psicológico en las organizaciones: un análisis desde los sectores económicos y productivos', 'http://hdl.handle.net/20.500.12442/2498', ''),
('Bioética y sus implicaciones en el derecho', 'https://hdl.handle.net/20.500.12442/6242', ''),
('Bioética y transversalidad educativa', '', 'Este libro no se terminó'),
('Caracterización de organizaciones del sector agropecuario. Zona rural del departamento del Atlántico-Colombia', 'https://hdl.handle.net/20.500.12442/3832', ''),
('Cátedra de estudios afrocolombianos en el contexto curricular del departamento del atlántico', 'https://hdl.handle.net/20.500.12442/3839', ''),
('Concepciones y prácticas en el contexto educativo de norte de santander', 'http://hdl.handle.net/20.500.12442/2507', ''),
('Condiciones de salud y trabajo de los fisioterapeutas en colombia', 'https://hdl.handle.net/20.500.12442/4169', ''),
('Contribución a la conservación de orchidiaceas de santander mediante cultivo in vitro de semillas', 'https://hdl.handle.net/20.500.12442/6243', ''),
('Crisis planetaria: el movimiento de la ecopedagogía', 'https://hdl.handle.net/20.500.12442/3750', ''),
('Cuotas de género y democracia paritaria. avances en los derechos políticos de las mujeres', 'https://hdl.handle.net/20.500.12442/4316', ''),
('Datos, información, tendencias, tres miradas sobre un contexto cambiante', 'https://hdl.handle.net/20.500.12442/3948', ''),
('De la teoría a la praxis: procesos complejos de enseñanza aprendizaje para una formación jurídica multidimensional', 'https://hdl.handle.net/20.500.12442/3779', ''),
('Descontaminando con microalgas', '', 'Este libro no se terminó'),
('Didácticas para la formación en finanzas en administración', 'https://hdl.handle.net/20.500.12442/4314', ''),
('Didácticas para procesos centrados en la enseñanza y/o aprendizaje', 'https://hdl.handle.net/20.500.12442/3754', ''),
('Diversas perspectivas educativas', 'https://hdl.handle.net/20.500.12442/3833', ''),
('Educación en resiliencia y construcción de paz en Colombia. Reflexiones en materia de formación docente para una ciudadanía planetaria', 'https://hdl.handle.net/20.500.12442/3794', ''),
('Educación transdisciplinar, tecno-didáctica y paradigmas emergentes: para una ciudadanía planetaria', 'https://hdl.handle.net/20.500.12442/3780', ''),
('Educación, cultura y sociedad: oportunidades para la investigación', 'https://hdl.handle.net/20.500.12442/3652', ''),
('El diccionario acerca de Don Quijote de la Mancha. Glosario enciclopédico', 'https://hdl.handle.net/20.500.12442/4313', ''),
('El nuevo orden jurídico educativo', '', 'Este libro no se terminó'),
('Ensamble cultural del caribe', 'https://hdl.handle.net/20.500.12442/3840', ''),
('Experiencia de prácticas profesorales significativas 2017', 'https://hdl.handle.net/20.500.12442/3838', ''),
('Formación en investigación: desarrollo de competencias investigativas. Reflexiones en materia de formación docente para una ciudadanía planetaria', 'https://hdl.handle.net/20.500.12442/3751', ''),
('Gestión del conocimiento, semilleros de investigación y procesos comunicativos aplicados al contexto educativo e institucionales', 'http://hdl.handle.net/20.500.12442/2514', ''),
('Inclusion and excellence in postconflict colombian higher education: views from the leadership', '', 'No en el repositorio'),
('Información, estructura y procedimiento', 'https://hdl.handle.net/20.500.12442/3469', ''),
('Innovaciones didácticas mediadas por las tecnologías digitales: reflexiones teórico- prácticas', 'https://hdl.handle.net/20.500.12442/3755', ''),
('Innovaciones educativas para favorecer los de lectoescritura: implementaciones prácticas', 'https://hdl.handle.net/20.500.12442/3758', ''),
('Interculturalidad e interdisciplinariedad en escenarios educativos', '', 'Este libro no se terminó'),
('La armonía entre las teoría y la práctica: formación docente', 'https://hdl.handle.net/20.500.12442/3756', ''),
('La construcción permanente de la cultura de paz', '', 'NO SUBIDO EN BONGA; Este libro no se terminó'),
('La convivencia escolar como estrategia para el fomento de las competencias ciudadanas en las instituciones educativas del país', 'https://hdl.handle.net/20.500.12442/3752', ''),
('La evaluación y el aprendizaje: una mirada holística', 'https://hdl.handle.net/20.500.12442/3746', ''),
('La inclusión: una base para la educación. Vías para la inclusión interdisciplinar', 'https://hdl.handle.net/20.500.12442/3757', ''),
('La internacionalización de las empresas versus el emprendimiento y la innovación', 'http://hdl.handle.net/20.500.12442/2515', ''),
('La investigación social: comprendiendo fenómenos en contexto', 'http://hdl.handle.net/20.500.12442/2485', ''),
('La migración: el desborde de un fenómeno masivo', 'http://hdl.handle.net/20.500.12442/2516', ''),
('La región caribe: una plataforma potencial para el desarrollo de sector logístico, el mercado del consumo masivo y el emprendimiento', 'https://hdl.handle.net/20.500.12442/6960', ''),
('La regulación aduanera colombiana frente al derecho marítimo internacional', 'https://hdl.handle.net/20.500.12442/3835', ''),
('Las tecnologías digitales como elemento transformador de la práctica educativa y los procesos de enseñanza aprendizaje', 'https://hdl.handle.net/20.500.12442/7061', ''),
('Las TIC como agente catalizador de enseñanza aprendizaje. Reflexiones en materia de formación docente para una ciudadanía planetaria', 'https://hdl.handle.net/20.500.12442/3748', ''),
('Liderazgo: tendencias emergentes para inspirar la gestión de personas en las organizaciones', 'https://hdl.handle.net/20.500.12442/3841', ''),
('Manumisión y abolición de la esclavitud en el Caribe Colombiano 1812 – 1852', 'https://hdl.handle.net/20.500.12442/3836', ''),
('Metateoria y praxis de la justicia restaurativa, ambiental y iusfilosófica. Tomo I.', 'https://hdl.handle.net/20.500.12442/3945', ''),
('Metateoría y praxis: sobre la memoria del conflicto armado, la paz, la inserción social y las nuevas postviolencia en el panóptico virtual. Tomo II', 'https://hdl.handle.net/20.500.12442/3837', ''),
('Modelos y tendencias en las prácticas docentes: Reflexiones en materia de formación docente para una ciudadanía planetaria', 'https://hdl.handle.net/20.500.12442/3781', ''),
('Nuevas tendencias del derecho en colombia', 'http://hdl.handle.net/20.500.12442/2493', ''),
('Panorama jurídico y sociojurídico de los derechos humanos, sociales y ambientales. Tomo I', 'https://hdl.handle.net/20.500.12442/3947', ''),
('Panorama jurídico y sociojurídico de los derechos humanos, sociales y ambientales. Tomo II', 'https://hdl.handle.net/20.500.12442/7063', ''),
('Patrimonios culturales del caribe colombiano', 'https://hdl.handle.net/20.500.12442/9646', ''),
('Políticas educativas: Una mirada al contexto colombiano', '', 'Este libro no se terminó'),
('Prácticas curriculares, cultura y procesos de formación', '', 'NO SUBIDO EN BONGA'),
('Prácticas educativas para el fomento de la calidad y la investigación: Reflexiones en materia de formación docente para una ciudadanía planetaria', 'https://hdl.handle.net/20.500.12442/3782', ''),
('Productividad, competitividad y creación de valor del sector agroexportador: un enfoque de los costos, la responsabilidad social y la gestión ambiental en la región caribe', 'https://hdl.handle.net/20.500.12442/3915', ''),
('Propuesta epistemológica para una práctica axiológica en la instrumentación quirúrgica', 'https://hdl.handle.net/20.500.12442/3946', ''),
('Reflexiones sobre las migraciones en américa latina', 'https://hdl.handle.net/20.500.12442/3919', ''),
('Reflexiones y estudios sobre la práctica pedagógica y la formación del ser', 'https://hdl.handle.net/20.500.12442/3920', ''),
('Reflexiones y prácticas: la creatividad en la educación', 'https://hdl.handle.net/20.500.12442/3744', ''),
('Resignificación de las representaciones sociales hacia la vejez. Un diálogo de saberes intergeneracionales: caso Colombia Barranquilla – Chile Chillán', 'http://hdl.handle.net/20.500.12442/2837', ''),
('Retos actuales en la enseñanza y aprendizaje de las matemáticas', 'https://hdl.handle.net/20.500.12442/3783', ''),
('Salud sexual y reproductiva construcción de cultura de paz y corresponsabilidad social', 'https://hdl.handle.net/20.500.12442/3914', ''),
('Significados y prácticas durante el asentimiento informado: una mirada externa a la autonomía y desarrollo moral del menor maduro', 'https://hdl.handle.net/20.500.12442/3793', ''),
('Sociedad y conflicto: una oportunidad para el aprendizaje', 'https://hdl.handle.net/20.500.12442/3753', ''),
('Sociedad y derecho', 'https://hdl.handle.net/20.500.12442/3464', ''),
('Sujeto y discursos alternativos', 'https://hdl.handle.net/20.500.12442/3916', ''),
('Sustentabilidad en las organizaciones. acciones y perspectivas del presente con visión de futuro', 'https://hdl.handle.net/20.500.12442/3917', ''),
('Territorios de resistencia e identidad en dos palenques urbanos en barranquilla (nueva colombia y mequejo)', 'https://hdl.handle.net/20.500.12442/3918', ''),
('Territorios: frontera, migración y realidad social', 'https://hdl.handle.net/20.500.12442/3281', 'PDF no disponible en Bonga'),
('Rafael Campo Miranda. Joya musical de Colombia: vida y obra', '', 'No hay ejemplares disponibles'),
('Factores percibidos por los ciudadanos para que sea efectiva la seguridad ciudadana en Barranquilla - Colombia', '', 'No existe este libro, es una tesis doctoral'),
('Formación de abogados: nuevos retos frente al desafío del derecho', 'https://hdl.handle.net/20.500.12442/9629', ''),
('El rostro de la violencia: el postconflicto colombiano y su impacto en la frontera colombo-venezolana (Apure-Arauca, Táchira – Norte de Santander)', 'https://hdl.handle.net/20.500.12442/3171', ''),
('Casos y experiencias significativas en torno a la educación y la movilidad social desde las políticas públicas, la innovación y el emprendimiento', 'https://hdl.handle.net/20.500.12442/7037', ''),
('Casos y experiencias significativas en torno a la educación y la movilidad social en las regiones', 'https://hdl.handle.net/20.500.12442/6962', ''),
('Desafíos de la educación y la movilidad social en Latinoamérica', 'https://hdl.handle.net/20.500.12442/7036', ''),
('Informe sobre la movilidad humana venezolana II. Realidades y perspectivas de quienes emigran (8 de abril al 5 de mayo de 2019)', 'https://hdl.handle.net/20.500.12442/4621', ''),
('Perfiles sociodemográficos de la migración venezolana, principales características según país receptor[8 de abril al 5 de mayo de 2019]', 'https://hdl.handle.net/20.500.12442/4675', ''),
('Estructuras organizacionales y competitividad. Una mirada a las medianas empresas', 'https://hdl.handle.net/20.500.12442/7270', ''),
('Políticas públicas de protección de la mujer y derechos humanos en Colombia', 'https://hdl.handle.net/20.500.12442/4727', ''),
('La escuela de la vida. L''ecole de la vie', 'https://hdl.handle.net/20.500.12442/4313', ''),
('Migración con ojos de mujer. Una mirada interseccional', 'https://hdl.handle.net/20.500.12442/4365', ''),
('Ser maestro: ser humano', 'https://hdl.handle.net/20.500.12442/4336', ''),
('Comportamiento del consumidor en el manejo de residuos eléctricos y electrónicos en la costa Caribe colombiana', 'https://hdl.handle.net/20.500.12442/6334', ''),
('Dinastía musical de Los Granados', '', 'No hay ejemplares disponibles'),
('Aspectos básicos de economía en el contexto internacional', 'https://hdl.handle.net/20.500.12442/6402', ''),
('Caracterización del perfil del docente de los programas de administración y sus competencias para la docencia en la región caribe colombiana', 'https://hdl.handle.net/20.500.12442/6557', ''),
('Estrategias lean para el fomento a la competitividad en las mipymes de la industria metalmecánica', '', 'Este libro es externo'),
('Estrés, salud y bienestar de las personas LGBT en Colombia. Resultados de una encuesta nacional', 'https://hdl.handle.net/20.500.12442/8296', ''),
('Estudios en las organizaciones públicas, privadas y sociales en América Latina y el Caribe : Un enfoque inter y transdisciplinario Tomo I', 'https://hdl.handle.net/20.500.12442/5835', ''),
('Estudios en las organizaciones públicas, privadas y sociales en América Latina y el Caribe : Un enfoque inter y transdisciplinario Tomo II', 'https://hdl.handle.net/20.500.12442/5839', ''),
('Fundamentos teóricos de la responsabilidad social. Una mirada organizacional', 'https://hdl.handle.net/20.500.12442/6403', ''),
('Lineamientos de política económica para la dolarización. Una aproximación para la experiencia venezolana', 'https://hdl.handle.net/20.500.12442/6404', ''),
('Macroproyecto de gestión curricular: ruta investigativa para definición de una política hasta su implementación', 'https://hdl.handle.net/20.500.12442/6236', ''),
('Mujeres ancestrales. Proyecto “Mujeres formadas para visibilizar la cultura ancestral hacia una vida libre de violencias y sin discriminación en el departamento del Atlántico”. Fase II', 'https://hdl.handle.net/20.500.12442/6798', ''),
('Prácticas de responsabilidad social en el contexto latinoamericano', '', 'Este libro no se terminó'),
('Programa de atención en Fisioterapéutica: para pacientes con Síndrome Doloroso Miofascial', '', 'Este libro no se terminó'),
('Programa de Atención Fisioterapéutica en pacientes con síndrome del manguito rotador', 'https://hdl.handle.net/20.500.12442/7235', ''),
('Intervención para la condición motriz en niños de 6 a 12 años. Programa de Atención Fisioterapéutica', 'https://hdl.handle.net/20.500.12442/6959', ''),
('School violence radiography', 'https://hdl.handle.net/20.500.12442/6955', ''),
('Mujer, género, movimientos feministas y políticas públicas de protección: Colombia y Venezuela', 'https://hdl.handle.net/20.500.12442/4403', ''),
('Camilo Namén Rapalino', '', 'Este libro es externo'),
('Estrategias de innovación y mejora curricular en la educación superior', 'https://hdl.handle.net/20.500.12442/6235', ''),
('Prácticas de ética y responsabilidad social en pequeñas empresas', 'https://hdl.handle.net/20.500.12442/7293', ''),
('Realidades y desafíos para el inmigrante venezolano tras la COVID-19', 'https://hdl.handle.net/20.500.12442/6240', 'Es un artículo'),
('Familia, política y construcción de ciudadanía', 'https://hdl.handle.net/20.500.12442/7234', ''),
('La legitimidad de la filosofía latinoamericana', 'https://hdl.handle.net/20.500.12442/6725', ''),
('Violencia política contra las mujeres', 'https://hdl.handle.net/20.500.12442/6732', ''),
('Prospectiva de la integración social de las mujeres colombianas con necesidad de protección internacional en Venezuela', 'https://hdl.handle.net/20.500.12442/7023', 'Es un artículo'),
('Bicentenario de Colombia Tomo VI. Episodios Nacionales III', 'https://hdl.handle.net/20.500.12442/6958', ''),
('Contemporaneidad del derecho laboral y la seguridad social en colombia. tomo i', 'https://hdl.handle.net/20.500.12442/7338', ''),
('Gestión ambiental para la implementación de Biodigestores Anaeróbicos. Reductores de residuos contaminantes en el medioambiente de los departamentos de la Región Norte y Central de Colombia', 'https://hdl.handle.net/20.500.12442/7340', ''),
('Laboratorio de biología programas: Enfermería, Fisioterapia, Instrumentación Quirúrgica, Microbiología', 'https://hdl.handle.net/20.500.12442/7239', ''),
('Plataforma tic para la toma de decisiones del sistema logístico portuario', 'https://hdl.handle.net/20.500.12442/695', ''),
('Relaciones y conexiones de los procesos investigativos: perspectivas ecocomunicativas transdisciplinares', 'https://hdl.handle.net/20.500.12442/6948', ''),
('Satisfacción laboral: un análisis desde los sectores económicos y productivos', 'https://hdl.handle.net/20.500.12442/7276', ''),
('Trabajo social caribe. Compresiones culturales e investigativas', 'https://hdl.handle.net/20.500.12442/6957', ''),
('Trabajo social: frontera, flujos migratorios y capitalismo global', 'https://hdl.handle.net/20.500.12442/7250', ''),
('Situación de la población colombiana con necesidad de protección Internacional en el Estado Táchira - Venezuela durante la COVID-19', 'https://hdl.handle.net/20.500.12442/7024', ''),
('Análisis situacional de salud del Corregimiento La Playa: Sectores la Cangrejera y Playita', 'https://hdl.handle.net/20.500.12442/7240', ''),
('Neuromarketing y honestidad empresarial. Una aplicación en el sector bancario', 'https://hdl.handle.net/20.500.12442/9641', ''),
('Pensamiento marítimo, portuario, fluvial, humanista, educativo y socioambiental en la Armada Nacional', 'https://hdl.handle.net/20.500.12442/7056', ''),
('Transformación socio jurídica, humanística y cientificista. tomo ii', 'https://hdl.handle.net/20.500.12442/9653', ''),
('Administración burocrática y política pública de ciencia tecnología e innovación. Las actitudes en el caso del departamento del Atlántico', 'https://hdl.handle.net/20.500.12442/7902', ''),
('Análisis de coyunturas fronterizas en y desde colombia', 'https://hdl.handle.net/20.500.12442/7228', ''),
('Avances investigativos en nefritis lúpica', 'https://hdl.handle.net/20.500.12442/9611', ''),
('Capacidad productiva de la población vulnerable económicamente activa en el departamento del atlántico', 'https://hdl.handle.net/20.500.12442/7243', ''),
('Contemporaneidad del Derecho Laboral y la Seguridad Social en Colombia. Tomo II', 'https://hdl.handle.net/20.500.12442/7226', ''),
('Contextos y realidades ciudadanas: bases para el desarrollo sostenible', 'https://hdl.handle.net/20.500.12442/7337', ''),
('Crisis ambiental: racionalidad, planteamiento dialógico por una nueva percepción ambiental', 'https://hdl.handle.net/20.500.12442/7058', ''),
('Cuidado de enfermería ser y esencia para promover la salud y bienestar', 'https://hdl.handle.net/20.500.12442/7230', ''),
('Depresión en cuidadores adscritos a centros de larga permanencia', 'https://hdl.handle.net/20.500.12442/7242', ''),
('Derechos humanos: prácticas, problemáticas y resistencias. Un análisis de contextos', 'https://hdl.handle.net/20.500.12442/7241', ''),
('El liderazgo en el desarrollo y la gestión de las organizaciones', 'https://hdl.handle.net/20.500.12442/7274', ''),
('Enfoque de género: una construcción hacia la igualdad', 'https://hdl.handle.net/20.500.12442/7738', ''),
('Estrategias para la construcción de paz en colombia: un enfoque multidisciplinar', 'https://hdl.handle.net/20.500.12442/7273', ''),
('Frontera y salud mental', 'https://hdl.handle.net/20.500.12442/7060', ''),
('Impacto de la logística e innovación en el comercio internacional', 'https://hdl.handle.net/20.500.12442/7339', ''),
('Incidencia de las NIIF en la toma de decisiones gerenciales de las cooperativas del sector salud: El caso de la Cooperativa Vida y Salud (Coovisa) de Barranquilla, Colombia', 'https://hdl.handle.net/20.500.12442/7059', 'Parece artículo'),
('Innovación educativa en contexto. Una mirada a la práctica docente desde la academia Tomo I', 'https://hdl.handle.net/20.500.12442/7899', ''),
('Innovación educativa en contexto. Una mirada a la práctica docente desde la academia Tomo II', 'https://hdl.handle.net/20.500.12442/7901', ''),
('Medioambiente: Sujeto de derechos', 'https://hdl.handle.net/20.500.12442/7062', ''),
('Métrica con calidad de servicio para el protocolo de enrutamiento RPL', 'https://hdl.handle.net/20.500.12442/11231', ''),
('Migración una mirada binacional desde lo humanitario', 'https://hdl.handle.net/20.500.12442/7757', ''),
('Movilizaciones humanas', 'https://hdl.handle.net/20.500.12442/7232', ''),
('Neurodesarrollo adolescente: perspectiva en la educación actual', 'https://hdl.handle.net/20.500.12442/7277', ''),
('Panorama actual de la educación inclusiva', 'https://hdl.handle.net/20.500.12442/7753', ''),
('Perspectivas sociales, jurídicas y económicas desde la frontera del norte de santander, colombia', 'https://hdl.handle.net/20.500.12442/7233', ''),
('Prácticas sociales de paz: la configuración de sujetos y escuelas creadoras de humanidad', 'https://hdl.handle.net/20.500.12442/7739', ''),
('Los procesos sociales en la gestión social universitaria', 'https://hdl.handle.net/20.500.12442/7251', ''),
('Propuesta pedagógica b-art. una guía para la formación integral e inclusiva del primer infante basada en expresiones del arte y el método aba', 'https://hdl.handle.net/20.500.12442/7237', ''),
('Relaciones padres e hijos un reto para las familias ensamblada', 'https://hdl.handle.net/20.500.12442/9652', ''),
('Relevo generacional en el sector artesanal', 'https://hdl.handle.net/20.500.12442/7903', ''),
('Residuos sólidos una alternativa de aprovechamiento para los municipios de Bolívar', 'https://hdl.handle.net/20.500.12442/7904', ''),
('Salud y cuidado en cursos de vida', 'https://hdl.handle.net/20.500.12442/7238', ''),
('Sistema escenarios de aprendizaje creativos: Circuitos y estaciones didácticas como estrategia humanizada para la Educación Superior', 'https://hdl.handle.net/20.500.12442/7236', ''),
('Tendencias de la administración global. Una mirada desde el emprendimiento social, innovación, estrategia, competitividad y bioeconomía', 'https://hdl.handle.net/20.500.12442/7275', ''),
('Manual psicoeducativo y con andamiaje tutorial para la prevención y resolución del mobbing y el bullying escolar', 'https://www.researchgate.net/publication/376481776_MANUAL_PSICOEDUCATIVO_Y_CON_ANDAMIAJE', 'Pacheco Bolaño, Janer'),
('Las familias transnacionales en la política pública colombiana. La invisibilidad de las familias en un sistema político que aún no las define', 'https://hdl.handle.net/20.500.12442/7091', ''),
('La hegemonía del management III', '', 'No esta publicado en Bonga'),
('Pinceladas de nuestra sociedad', 'https://hdl.handle.net/20.500.12442/7224', ''),
('Aproximaciones epistemológicas y teóricas de las acciones investigativas en el doctorado en psicología', 'https://hdl.handle.net/20.500.12442/9602', ''),
('La tríada entre consultorio jurídico, investigación y comunidad', 'https://hdl.handle.net/20.500.12442/9637', ''),
('Consecuencias de la rivalidad entre Simón Bolívar y Manuel del Castillo', '', 'Carlos Rodado Noriega'),
('Educación, prácticas pedagógicas alternativas', 'https://hdl.handle.net/20.500.12442/7981', ''),
('Entornos educativos y filosofía de la formación. sobrevuelos, incertidumbres y aportes para una nueva racionalidad pedagógica', 'https://hdl.handle.net/20.500.12442/7992', ''),
('Educación, confianza y vida', 'https://hdl.handle.net/20.500.12442/8205', ''),
('Gestión de marketing en la era digital: estrategias para microempresas frente a la incidencia económica del covid-19', 'https://hdl.handle.net/20.500.12442/7962', ''),
('Violencia contra la mujer: venezolanas y colombianas con necesidad de protección internacional (PNPI) en los Estados Barinas y Táchira (Venezuela) Propuestas para un cambio', 'https://hdl.handle.net/20.500.12442/7900', ''),
('Dialéctica constitucional', 'https://hdl.handle.net/20.500.12442/9619', ''),
('Garantismo del derecho constitucional', 'https://hdl.handle.net/20.500.12442/9634', ''),
('Derechos sexuales y reproductivos en mujeres migrantes venezolanas en tiempos de COVID-19. Desafíos para su implementación', 'https://hdl.handle.net/20.500.12442/8116', ''),
('Informe de movilidad humana venezolana III. Caminantes y retornados, dos realidades del venezolano en pandemia (12 de mayo al 30 de junio 2021)', 'https://hdl.handle.net/20.500.12442/8115', ''),
('Futuros de la educación en contextos de incertidumbres: construcciones desde las nuevas humanidades', 'https://hdl.handle.net/20.500.12442/10351', ''),
('Preparación para la maternidad y la paternidad. Cursos en circuitos y estaciones interactivas para profesionales de la salud RIAS materno perinatal', 'https://hdl.handle.net/20.500.12442/9649', ''),
('Realidades contemporáneas desde el enfoque de los derechos humanos', 'https://hdl.handle.net/20.500.12442/9651', ''),
('Informe de Movilidad Humana Venezolana IV. Caminantes y retornados: ilusión y decepción (01 de Julio al 30 de Septiembre 2021)', 'https://hdl.handle.net/20.500.12442/9523', ''),
('Enfermedad de Huntington: una aproximación desde la investigación', 'https://hdl.handle.net/20.500.12442/11816', ''),
('Los principios de mediación y conciliación en América Latina y el Caribe : Análisis comparado a partir de la Ley modelo de la CNUDMI sobre mediación comercial internacional y acuerdos de transacción internacionales resultantes de la mediación', 'https://hdl.handle.net/20.500.12442/10117', ''),
('Transformación Socio Jurídica, Humanística y Cientificista, Tomo I', 'https://hdl.handle.net/20.500.12442/9650', ''),
('El sistema educativo indígena propio fortalece el proyecto educativo comunitario intercultural mokaná', 'https://hdl.handle.net/20.500.12442/8507', ''),
('Abandona el cigarrillo y retoma tu vida', 'https://hdl.handle.net/20.500.12442/11701', ''),
('El enfoque interseccional en el estudio de las dinámicas de las violencias contra las mujeres en el departamento de la guajira', 'https://hdl.handle.net/20.500.12442/11208', ''),
('Gestión empresarial. Casos de enseñanza sobre decisiones y estrategias', 'https://hdl.handle.net/20.500.12442/15527', ''),
('Derechos humanos de las mujeres y de la comunidad LGTBI', 'https://hdl.handle.net/20.500.12442/11209', ''),
('Informe de movilidad humana venezolana V. Caminantes: un peregrinaje que no se detiene (1º de octubre de 2021 al 31 de marzo de 2022)', 'https://hdl.handle.net/20.500.12442/9654', ''),
('Comunicación con enfoque de género', 'https://hdl.handle.net/20.500.12442/11210', ''),
('Nuevas narrativas comunitarias ICBF, Ariguaní, Nueva Granada y San Ángel (Magdalena)', 'https://hdl.handle.net/20.500.12442/9757', ''),
('El barrio modelo. retrospectiva histórico-cultural de un barrio con corazón barranquillero', 'https://hdl.handle.net/20.500.12442/9817', ''),
('Profesionalización gerencial. oportunidad para liderar y dirigir empresas', 'https://hdl.handle.net/20.500.12442/10372', ''),
('Buenas prácticas para la internacionalización del currículo: “Experiencias en la Universidad Simón Bolívar”', 'https://hdl.handle.net/20.500.12442/11268', ''),
('Fragmentos históricos. Tomo 2', 'https://hdl.handle.net/20.500.12442/11236', ''),
('Tratamiento quirúrgico de la mano traumatizada', '', 'Ejemplar no disponible en Bonga'),
('Bicentenario de colombia 1810-2010. tomo vii episodios nacionales IV', 'https://hdl.handle.net/20.500.12442/11269', ''),
('Por los caminos de la hamaca grande', '', 'Ejemplar no disponible en Bonga'),
('Informe de movilidad humana venezolana VII. Caminantes en retorno: trabajo y ocupación (1º de agosto al 30 de septiembre 2022)', 'https://hdl.handle.net/20.500.12442/11598', ''),
('Elementos de filosofía. beato josé gregorio hernández cisneros', 'https://hdl.handle.net/20.500.12442/11497', 'Externo'),
('Políticas públicas sobre educación superior en colombia', '', 'Ejemplar no disponible en Bonga'),
('Violencia intrafamiliar, violencia de género y violencia contra las mujeres. ¿distintas formas de nombrar un problema?', 'https://hdl.handle.net/20.500.12442/11205', ''),
('Competencias en fisioterapia digital para colombia', 'https://hdl.handle.net/20.500.12442/11670', ''),
('Dinámicas de las violencias contra las mujeres en el departamento de La Guajira', 'https://hdl.handle.net/20.500.12442/11680', ''),
('Recomendaciones y plan de manejo para paciente confirmado y sospechoso covid- 19', 'https://hdl.handle.net/20.500.12442/11832', ''),
('Residuos de madera: impacto social, económico y ambiental', 'https://hdl.handle.net/20.500.12442/11687', ''),
('Violencia contra las mujeres por razones de género', 'https://hdl.handle.net/20.500.12442/11206', ''),
('Escuela abierta', 'https://hdl.handle.net/20.500.12442/12401', 'Externo'),
('La trata de personas. una forma moderna de esclavitud', 'https://hdl.handle.net/20.500.12442/11207', ''),
('El trono y sus razones. semántica y procesos en las políticas públicas', 'https://hdl.handle.net/20.500.12442/12427', ''),
('Desarrollo estratégico del archipiélago de san andrés, providencia y santa catalina', 'https://hdl.handle.net/20.500.12442/13385', ''),
('Gobierno institucional en la educación superior: perspectivas y retos en contextos de cambio', 'https://hdl.handle.net/20.500.12442/12019', ''),
('Cátedra ancestralidad y afrodescendencia. aquiles escalante polo: vida y obra', 'https://hdl.handle.net/20.500.12442/12398', 'Este libro es de divulgación'),
('Eco muebles una estrategia para el aprovechamiento de residuos sólidos', 'https://hdl.handle.net/20.500.12442/11923', ''),
('Fortaleciendo nuestra identidad Caribe : Sistematización de trabajos de soporte investigativo de la puesta en escena de grupos culturales universitarios de la Red de Bienestar Nodo Caribe, ASCUN Cultura. Tomo I - Danzas patrimoniales y música folclórica', 'https://hdl.handle.net/20.500.12442/12433', ''),
('Transformando los conflictos de pareja desde el control emocional y la resiliencia', 'https://hdl.handle.net/20.500.12442/12161', ''),
('Alianzas Empresariales. Un enfoque desde el pensamiento estratégico, para la consolidación del sector turístico', 'https://hdl.handle.net/20.500.12442/12749', ''),
('Experiencias de la pandemia COVID-19 Colombia 2020-2022', 'https://hdl.handle.net/20.500.12442/12790', ''),
('Mujer ariguanense en 100 palabras', 'https://hdl.handle.net/20.500.12442/12937', ''),
('Bicentenario de Colombia 1810-2010. Tomo VIII Episodios Nacionales V', 'https://hdl.handle.net/20.500.12442/14030', ''),
('El discurso filosófico frente al hombre II parte. Entre lo real e irreal o entre lo racional e irracional y lo virtual', 'https://hdl.handle.net/20.500.12442/14033', ''),
('Migración venezolana  en el territorio fronterizo de Norte de Santander, Colombia. Subjetividades, tránsitos y devenires', 'https://hdl.handle.net/20.500.12442/13360', ''),
('Asesoramiento científico a la política pública exterior', 'https://hdl.handle.net/20.500.12442/13430', ''),
('Desarrollo de publicaciones de alto impacto', 'https://hdl.handle.net/20.500.12442/13433', ''),
('Diplomacia científica y relacionamiento estratégico', 'https://hdl.handle.net/20.500.12442/13431', ''),
('Recursos internacionales para proyectos de investigación', 'https://hdl.handle.net/20.500.12442/13432', ''),
('Factores socioculturales de la morbimortalidad materno infantil: comunidad wayuu, jurisdicción de nazareth, municipio de uribía, departamento de la guajira', 'https://hdl.handle.net/20.500.12442/13392', ''),
('Educar en el siglo XXI: reflexiones y percepciones desde la  digitalización hasta la inclusión', 'https://hdl.handle.net/20.500.12442/13427', ''),
('Análisis de las condiciones del transporte en el área  metropolitana: percepción de los estudiantes', 'https://hdl.handle.net/20.500.12442/13774', ''),
('Análisis de las condiciones del transporte en el área  metropolitana: percepción de los transportadores', 'https://hdl.handle.net/20.500.12442/13774', ''),
('Ruta participativa Pacto por la Educación: estrategias y apuestas metodológicas  para la co-creación de una región educadora', 'https://hdl.handle.net/20.500.12442/14220', ''),
('Documento Técnico. Política Pública Educativa para Norte de Santander. Nuevo modelo  educativo con visión 2050. Por una región educadora', 'https://hdl.handle.net/20.500.12442/14219', ''),
('Estación Arte: Pilote Cultural Caribe', 'https://hdl.handle.net/20.500.12442/15630', ''),
('Experiencias ondas norte de santander 2023', 'https://hdl.handle.net/20.500.12442/14999', ''),
('Ciencia, academia y vida: análisis de nuestra realidad', 'https://hdl.handle.net/20.500.12442/15887', ''),
('Trazando poéticas de cuidado y re-existencia de las mujeres. Legado, permanencia y nuevas perspectivas en las investigaciones feministas de la RED-HILA', 'https://hdl.handle.net/20.500.12442/14520', ''),
('Hacia una región educadora: ecosistema de investigación e innovación desde las aulas', 'https://hdl.handle.net/20.500.12442/14220', ''),
('Aktuelle Herausforderungen für den Schutz der Menschenrechte:  Brasilianische Perspektiven', 'https://hdl.handle.net/20.500.12442/14627', ''),
('Convergencias migratorias: experiencias y reflexiones en ciudades fronterizas de América Latina', 'https://hdl.handle.net/20.500.12442/15979', ''),
('Conectando puntos: Inteligencia Artificial, datos y su impacto en la sostenibilidad. Memorias del Encuentro Internacional Inteligencia Artificial. Impacto de los datos en la sostenibilidad de las organizaciones', 'https://hdl.handle.net/20.500.12442/16118', ''),
('Historia y actualización de la Vasculitis e historias afines IV', 'https://www.amazon.com/HISTORIA-ACTUALIZACI%C3%93N-VASCULITIS-ENFERMEDADES-Spanish-ebook/dp/B0DXVXJGPS', 'Antonio Iglesias Gamarra'),
('Historias de resiliencia: artesanía y manifestación cultural en el municipio de puerto colombia (Atlántico)', 'https://hdl.handle.net/20.500.12442/16183', ''),
('Contra el silenciamiento y la invisibilización: muchas formas de resistencia cultural', 'https://hdl.handle.net/20.500.12442/16433', ''),
('Corazón de acordeón', 'https://hdl.handle.net/20.500.12442/16394', ''),
('Tomo conmemorativo año del centenario José Consuegra Higgins 1924-2024', 'https://hdl.handle.net/20.500.12442/16371', ''),
('Estrategias financieras y aspectos fiscales del sector empresarial en Colombia', 'https://hdl.handle.net/20.500.12442/16467', ''),
('Ecosistema en movimiento emergente. Creación de emprendimientos tecnológicos en territorios de bajo desempeño innovador', 'https://hdl.handle.net/20.500.12442/16925', ''),
('Explorando la biología desde la experimentación', 'https://hdl.handle.net/20.500.12442/16937', ''),
('Prevención de la trata de personas: Estrategias comunitarias y políticas  públicas para enfrentar un delito en expansión', 'https://hdl.handle.net/20.500.12442/16936', 'Es un Policy brief. Aunque aparece en los apartados de libro, no se debería catalogar. Tampoco tiene ISBN'),
('Experiencia significativa: educación como función social', 'https://hdl.handle.net/20.500.12442/17028', ''),
('Experimentos de física de ondas y partículas', 'https://hdl.handle.net/20.500.12442/17010', ''),
('Experimentos de física mecánica', 'https://hdl.handle.net/20.500.12442/17025', ''),
('Experimentos de física: electricidad y magnetismo', 'https://hdl.handle.net/20.500.12442/17026', ''),
('Hablando con máquinas', 'https://hdl.handle.net/20.500.12442/17031', ''),
('Los cimientos epistemológicos de la administración: Objeto, estatuto científico, desarrollo disciplinar y metodología', 'https://hdl.handle.net/20.500.12442/17096', ''),
('Pinceladas de valores y costumbrismo', 'https://hdl.handle.net/20.500.12442/17097', 'PDF no disponible en Bonga'),
('Gobierno y gobernanza de la educación superior en Iberoamérica: teorías, prácticas', 'https://hdl.handle.net/20.500.12442/17324', '');

-- Update repository_url where it's NULL and we have a URL
UPDATE books b
SET repository_url = m.new_url
FROM _migration m
WHERE LOWER(TRIM(b.title)) = LOWER(m.title_match)
  AND m.new_url != ''
  AND b.repository_url IS NULL;

-- Update notes where it's empty and we have notes  
UPDATE books b
SET notes = m.new_notes
FROM _migration m
WHERE LOWER(TRIM(b.title)) = LOWER(m.title_match)
  AND m.new_notes != ''
  AND (b.notes IS NULL OR b.notes = '');

DROP TABLE _migration;

SELECT 
  (SELECT COUNT(*) FROM books WHERE repository_url IS NOT NULL) as books_with_url,
  (SELECT COUNT(*) FROM books WHERE notes IS NOT NULL AND notes != '') as books_with_notes;
